### ISSUE TITLE
Design document comments

### ISSUE THREAD

**Issue by joseph-hellerstein** [tejasmhos/seattlecollision#1]
Your use case document is great. The design seems to be interwoven with the requirements? Could you separate this out so that the components are clear? In particular, it should be clear what components are common across the use cases so that you design with the appropriate level of generality.

**Comment by tejasmhos** [comment]
We fixed our documentation and made all the changes that you suggested.

**Comment by iankirkman** [comment]
Leaving issue open because we need to update the document to reflect design decisions that were made.

**Comment by iankirkman** [comment]
Dan, Alyssa, and Ian have todos left in the design document update. I am tracking those changes and will close the ticket when we are complete.
