### ISSUE TITLE
component design documentation

### ISSUE THREAD

**Issue by alyssacolony** [tejasmhos/seattlecollision#21]
Would you mind formating the component design document input section for query_class in the same style as the inputs in the rest of the document? Bullets instead of table. The instructors indicated that consistency is important and i think its easier to change your one, than to change the other five modules. Thanks .

**Comment by iankirkman** [comment]
I switched to bullets to be consistent with the rest of the doc. The lines are a little on the long side, because they include info about valid values and defaults. But I think that level of detail should stay, because it is important for how the query is interacted with.
