### ISSUE TITLE
Remaining to dos for project - Sign up

### ISSUE THREAD

**Issue by alyssacolony** [tejasmhos/seattlecollision#6]
*Requirements*
- Finish readme including: Installations (Done) Examples of how to use (Done), Project History (Alyssa), Limitations (TBD), Acknowledgments (TBD), Contact (TBD)
- Done - Finish requirements.txt (Dan) 
- Done - Put link to jupyter notebook in example folder (TBD)
- Done -  Update functional 'users' specification (Alyssa)
- Duplicated Ticket - Update design 'modules' specification (all)
- Done-ish? - Complete setup.py (Dan)
- Update Slides (Dan)
- New flow chart (Dan)
- Pylint (everyone)

*Nice to have: (In order of priority)*
- Add legend to map (Alyssa)
- Add brief commentary to Jupyter notebook adding a little more explanation of what things are.  e.g., what does collision interval and radius from building really mean? (Alyssa)
- Not doing - change query to allow for "all" option in base year selection 
- Improve widgit formatting so names aren't cut off (Ian)
- Add map tile interaction functionality to address the zoom problem. (Alyssa)

**Comment by iankirkman** [comment]
Will close soon when these are split into many tickets and assigned.
