### ISSUE TITLE
Slide deck update

### ISSUE THREAD

**Issue by iankirkman** [tejasmhos/seattlecollision#9]
1. Incorporate slides into google doc
2. Update Environment slide
3. Lessons/future work slide (with changes slide in separate ticket)
4. Incorporate Ian's slide updates

**Comment by iankirkman** [comment]
Speaking/slides order:

Use cases - Alyssa
Demo - Alyssa
Environment - Dan
Data - Dan
<transition flow chart>
Design - Ian
Travis - Ian
Shablona - Ian
Project Structure - Ian
Lessons/Changes/Future - Dan

**Comment by iankirkman** [comment]
Slides sent last night. 

Some future work ideas:

- More widget control/styling, adding multiple selects (which is supported by CollidiumQuery)
- More object-oriented project structure: using classes for Use Cases and Maps, this was limited by interact usage but potentially possible with expanded widget control
- Generalize CollidiumQuery args, maybe use dict structure for attributes and simplify set_attribute routines

**Comment by iankirkman** [comment]
Lessons Learned:

- Travis hangs for a long time when you have lots of commits close together and time-extensive testing

**Comment by iankirkman** [comment]
Reopening because that was an accidental closure... Just meant to add the comment.

**Comment by iankirkman** [comment]
@dwhite105 check layouts on slides 12, 13, and 15. The titles are getting covered when I view them. Also, see the lessons learned comment above.

**Comment by dwhite105** [comment]
Presentation complete! Nice job everyone!
